FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y rake uglifyjs.terser build-essential

COPY . /repo
WORKDIR /repo
RUN rake posix
WORKDIR /repo/posix
RUN rake test

FROM ubuntu:20.04 as package
COPY --from=builder /repo/posix/bin/test_h264bsd /
